# 日志等级
logging:
  level:
    root: info
    org:
      springframework: debug
    com.cac: debug

yiyan:
  security:
    resource-id: ${spring.application.name:system}
    token-info-uri: http://10.1.1.120:39996/oauth/check_token
    client-id: c1
    client-secret: secret
  feign:
#    system-path: http://10.1.1.120:31104/yiyan-system
#    auth-path: http://10.1.1.120:31104/yiyan-auth
#    file-path: http://10.1.1.120:31104/yiyan-file
    system-path: http://10.1.1.120:39996/yiyan-system
    auth-path: http://10.1.1.120:39996/yiyan-auth
    file-path: http://10.1.1.120:39996/yiyan-file
  error-code:
    enabled: false


feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: full # 日志级别，BASIC就是基本的请求和响应信息
        read-timeout: 0


server:
  port: 8080
# 本地环境不注册到nacos
spring:
  cloud:
    nacos:
      discovery:
        register-enabled: false
#    bus:
#      enabled: false # 是否开启，默认为 true
#      id: ${spring.application.name}:${server.port} # 编号，Spring Cloud Alibaba 建议使用“应用:端口”的格式
#      destination: springCloudBus # 目标消息队列，默认为 springCloudBus
---
# Actuator 监控端点的配置项
#management:
#  endpoints:
#    web:
#      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
#      exposure:
#        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
#
## Spring Boot Admin 配置项
#spring:
#  boot:
#    admin:
#      # Spring Boot Admin Client 客户端的相关配置
#      client:
#        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path} # 设置 Spring Boot Admin Server 地址
#        instance:
#          service-host-type: IP # 注册实例时，优先使用 IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
#      # Spring Boot Admin Server 服务端的相关配置
#      context-path: /admin # 配置 Spring
